import Link from "next/link";
import "./docs.css";

const groups = [["GETTING STARTED", [["introduction", "Introduction"], ["quickstart", "Quickstart"]]], ["CONCEPTS", [["dependency-states", "Dependency states"], ["agent-panel", "The agent panel"], ["verdicts", "Verdicts & policy"]]], ["TEAM WORKFLOWS", [["workspace-trust", "Workspace trust"], ["cli", "CLI reference"]]]] as const;
function Code({ children }: { children: string }) { return <pre className="docs-code"><code>{children}</code><button aria-label="Copy code">Copy</button></pre>; }

export default function DocsPage() {
  return <main className="docs-page"><aside className="docs-sidebar" aria-label="Documentation navigation"><div className="docs-sidebar-title"><span className="docs-dot" /> Locksmith docs</div><p className="docs-version">v0.1 · HACKATHON PREVIEW</p><nav>{groups.map(([group, items]) => <div className="docs-nav-group" key={group}><p>{group}</p>{items.map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</div>)}</nav><Link className="docs-sidebar-cta" href="/review">Open a review <span>↗</span></Link></aside>
    <article className="docs-content"><div className="docs-breadcrumb"><span>LOCKSMITH</span><span>/</span><b>DOCUMENTATION</b></div><header className="docs-intro" id="introduction"><p className="eyebrow">Dependency safety, explained</p><h1>Put dependency changes<br /><em>on trial.</em></h1><p className="docs-lede">Locksmith reviews the exact dependency state entering your repo. Six specialist Qwen agents gather evidence, challenge each other, and issue a decision your team can act on.</p><div className="docs-meta"><span><i className="status-dot" />DOCUMENTATION</span><span>Updated Jul 14, 2026</span></div></header>
      <section className="docs-section" id="quickstart"><div className="docs-section-label">01<span>Quickstart</span></div><div><h2>Get your first verdict in under a minute.</h2><p>Import a public GitHub repository, or run Locksmith locally before an install. The web review is the fastest way to see the full agent society in action.</p><Code>{"# local project\nnpx locksmith scan .\n\n# review a package file\nnpx locksmith review package-lock.json"}</Code></div></section>
      <section className="docs-section" id="dependency-states"><div className="docs-section-label">02<span>Core concept</span></div><div><h2>Reviews belong to dependency states.</h2><p>A package is not “safe forever.” Locksmith fingerprints the repo, commit, package manager, dependency files, and lockfile hashes. The same state resolves to the same review, whether it starts in the web app or the CLI.</p><div className="docs-callout"><strong>state_7f3a…</strong><span>repo + commit + package manager + file hashes</span><b>→</b><em>reviewed evidence</em></div></div></section>
      <section className="docs-section" id="agent-panel"><div className="docs-section-label">03<span>Agent society</span></div><div><h2>Six reviewers. One resolved verdict.</h2><p>Each agent owns a distinct question. Their findings stay visible so you can see the disagreement, the evidence that changed the room, and the Judge’s reasoning.</p><div className="agent-grid">{["Baseline", "Manifest", "Static", "Behavior", "Skeptic", "Judge"].map((agent, i) => <div key={agent}><span>0{i + 1}</span><b>{agent} Agent</b><small>{["What changed?", "Does it fit?", "What can it do?", "What does it do?", "Is this fair?", "What should we do?"][i]}</small></div>)}</div></div></section>
      <section className="docs-section" id="verdicts"><div className="docs-section-label">04<span>Decisioning</span></div><div><h2>Clear outcomes, grounded in policy.</h2><p>Judge combines evidence with your workspace policy. Critical findings block; medium findings ask for review; clean changes can be allowed.</p><div className="verdict-row"><span className="allow">ALLOW <small>clean or approved</small></span><span className="review">REVIEW <small>human confirmation</small></span><span className="block">BLOCK <small>critical evidence</small></span></div></div></section>
      <section className="docs-section" id="workspace-trust"><div className="docs-section-label">05<span>Team workflows</span></div><div><h2>Global evidence is not team approval.</h2><p>Public package facts can be reused. A workspace still makes its own trust decision for its own repo, branch, policy, and state. Commit the pointer, keep the full dossier in the evidence vault.</p><Code>{".locksmith/locksmith.json\n\n{\n  \"dependencyStateId\": \"state_7f3a…\",\n  \"verdict\": \"allow\",\n  \"policy\": \"strict\"\n}"}</Code></div></section>
      <section className="docs-section docs-last" id="cli"><div className="docs-section-label">06<span>CLI reference</span></div><div><h2>Guard the install, not just the review.</h2><p>Use the CLI in local development or CI. Locksmith checks the current state against workspace approval, then focuses the next review on new and risky changes.</p><div className="command-list"><code><b>locksmith scan .</b><span>Scan the current project</span></code><code><b>locksmith review package-lock.json</b><span>Review a dependency file</span></code><code><b>locksmith npm install</b><span>Guard an install (coming soon)</span></code></div></div></section><footer className="docs-footer"><span>LOCKSMITH / DOCS</span><Link href="/review">Start a review →</Link></footer></article></main>;
}
